---
- name: Create users
  hosts: localhost
  become: true

  tasks:
    - user: 
        name: damian
        uid: 1000
        shell: /bin/bash
    - user:
        name: blafoo
        uid: 1002
        shell: /bin/bash
